version: '2'
services:
  api:
    image: openjdk:8
    working_dir: /usr/src/app
    command: ./gradlew clean bootRun
    volumes:
      - .:/usr/src/app
    ports:
      - 8080:8080
      - 5005:5005
    links:
      - db:database
    env_file: .env
  db:
    image: postgres:9.6
    ports:
      - 5432:5432
    env_file: .env

